// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShareProfile contains the generated BPF and only the metadata needed by the UI.
 */
export interface ShareProfile {
    "name": string;
    "filename": string;
    "data": string | null;
    "size": number;
}
