// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * ShareService owns filesystem access and sing-box BPF handling.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function LoadConfig(path: string): $CancellablePromise<$models.ShareProfile | null> {
    return $Call.ByID(63614013, path);
}

export function OpenConfig(): $CancellablePromise<$models.ShareProfile | null> {
    return $Call.ByID(849574505);
}

/**
 * SaveBPF writes the exact bytes currently held by the frontend. The bool is
 * false only when the native save dialog is cancelled.
 */
export function SaveBPF(data: string | null, suggestedName: string): $CancellablePromise<boolean> {
    return $Call.ByID(2366846882, data, suggestedName);
}

/**
 * StartupProfile returns the command-line profile at most once.
 */
export function StartupProfile(): $CancellablePromise<$models.ShareProfile | null> {
    return $Call.ByID(2125556797);
}
